config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :posts do
    resources :comments

    collection do
        get :about
    end

    member do
      post :favourite
      post :unfavourite
      post :like
      post :dislike
      post :subscribe
      post :unsubscribe
    end

  end
  get '/profile/:id' => 'profiles#info', :as => "profile_info"

  namespace :admin do
    resources :posts # default ,:controller => "admin::posts"
    resources :users
    resources :categories
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :content
  #validates_nume_of

  belongs_to :post, :counter_cache => true
  belongs_to :user

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :set_post



  def show

  end


  def new
    @comment = @post.comments.new

  end

  def edit

  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      # TODO define a new method for updating comment time
      # def update_comment_time(options = {})
      #   self.update!(:last_comment_at = comment.updated_at )
      # end
      # e.g. @post.update_comment_time(:comment => @comment)
      @post.comment_last_updated_at = @comment.updated_at
      @post.save
      redirect_to post_path(@post)
    else
      render :action => :new
    end
  end

  def edit
    if current_user.author?(@post)||current_user.admin?
      # Same as posts#edit
      @comment = @post.comments.find(params[:id])
    else

      flash[:alert] = "not authorized"
      redirect_to post_path(@post)
    end
  end

  def update
    @comment = @post.comments.find(params[:id])
    if params[:destroy_logo]
      @comment.logo = nil
      @comment.save
    end
    if @comment.update(comment_params)
      @post.comment_last_updated_at = @comment.updated_at # TODO
      @post.save
      redirect_to post_path(@post)
    else
      render :action => :edit
    end
  end

  def destroy

    if current_user.author?(@post)||current_user.admin?
    # TODO
      @comment = @post.comments.find(params[:id])
      @comment.destroy

      if @post.comments_count > 1
        # @post.update_comment_time!(Comment.order("updated_at").last)
        @post.comment_last_updated_at = Comment.order("updated_at").last.updated_at
      else
        @post.comment_last_updated_at = nil
      end
      @post.save

    else
      flash[:alert] = "Not authorized"
    end

    redirect_to post_path(@post)
  end

  protected

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :logo)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div>
  <%= f.label :content, "Comment:" %>
  <%= f.text_area :content %>
</div>

<div class="form-group">
  <%= f.label :logo, "LOGO檔案" %>
  <%= f.file_field :logo %>
  <% if @comment.logo.exists? %>
    <%= check_box_tag "destroy_logo", "1" %> 刪除檔案
  <% end %>
</div>

app/views/comments/edit.html.erb
<%= form_for @comment, :url => post_comment_path(@post, @comment), :html => { :method => :patch } do |f| %>

  <%= render :partial => "form", :locals => {:f => f} %>

  <%= f.submit "Update" %>

<% end %>

<%= link_to "back", post_path(@post) %>

app/views/comments/new.html.erb
<%= form_for @comment, :url => post_comments_path(@post) do |f|  %>

  <%= render :partial => "form", :locals => {:f => f} %>

  <%= f.submit "Create" %>

<% end %>

<%= link_to "back", post_path(@post) %>