config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :posts do
    resources :comments

    collection do
        get :about
    end

    member do
      post :favourite
      post :unfavourite
      post :like
      post :dislike
      post :subscribe
      post :unsubscribe
    end

  end
  get '/profile/:id' => 'profiles#info', :as => "profile_info"

  namespace :admin do
    resources :posts # default ,:controller => "admin::posts"
    resources :users
    resources :categories
  end

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title

  has_many :comments, :dependent => :destroy

  has_many :post_categoryships
  has_many :categories, :through => :post_categoryships

  belongs_to :user

  has_many :favourite_posts, :dependent => :destroy
  has_many :favourite_by, :through => :favourite_posts, :source => :user, :dependent => :destroy

  has_many :likes, :dependent => :destroy
  has_many :likes_by, :through => :likes, :source => :user, :dependent => :destroy

  has_many :subscribes, :dependent => :destroy
  has_many :subscribes_by, :through => :subscribes, :source => :user, :dependent => :destroy

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  def find_my_favourite(user)

    self.favourite_posts.where(:user => user).first
  end

  def find_my_like(user)
    self.likes.where(:user => user).first
  end

  def find_my_subscribe(user)
    self.subscribes.where(:user => user).first
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"

  def index
    @posts = Post.all

  end





  def check_admin
    unless current_user.admin?
      raise ActiveRecord::RecordNotFound
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, :only => [:show, :edit, :update, :destroy, :favourite, :unfavourite, :like, :dislike, :subscribe, :unsubscribe]
  before_action :authenticate_user!, :except => [:index, :show]

  def index

    if params[:sort]&&params[:sort] == "Ruby"
      @posts = Category.find_by(:name =>"Ruby").posts
    elsif params[:sort]&&params[:sort] == "Perl"
      @posts = Category.find_by(:name =>"Perl").posts
    elsif params[:sort]&&params[:sort] == "Java"
      @posts = Category.find_by(:name => "Java").posts
    else
      @posts = Post.all.order("updated_at DESC")
    end

    if current_user &&current_user.admin?
      @posts = Post.all.order("updated_at DESC")
    elsif current_user
      @posts = @posts.where("user_id = ? or status = ?", current_user.id, "release")
    elsif
      @posts = @posts.where("status = 'release'")
    end

    if params[:order]
      if params[:order] == 'last_comment_time'
        @posts = @posts.order("comment_last_updated_at DESC")
      elsif params[:order] && params[:order] == 'comment_number'
        @posts = @posts.order("comments_count DESC")
      elsif params[:order] && params[:order] == "topic_clicks"
        @posts = @posts.order("clicked DESC")
      end
    end

    @posts = @posts.page(params[:page]).per(6)
    @categories = Category.all

  end

  def show

    @post.clicked += 1
    @post.save



    @comments = @post.comments.where("user_id = current_user.id").order("updated_at desc")

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save

      flash[:notice] = "Post was successfully created"
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    unless current_user.author?(@post)||current_user.admin?
      flash[:alert] = "Not authorized"
      redirect_to posts_path
    end
  end

  def update
    if @post.update(post_params)
      if params[:destroy_logo]
          @post.logo = nil
          @post.save
      end
        flash[:notice] = "Update successfully"
        redirect_to posts_path
    else
       render :action => :edit
    end
  end

  def destroy

    if current_user.author?(@post)||current_user.admin?
      @post.destroy
      flash[:alert] = "The post was successfully deleted"
    else
      flash[:alert] = "Not authorized"
    end
    redirect_to posts_path
  end

  def about
    @users = User.all
    @posts = Post.all
    @comments = Comment.all
  end

  def favourite

    @favourite = @post.find_my_favourite(current_user)
    unless @favourite
      @favourite = FavouritePost.create!(:post => @post, :user => current_user)
    end
    respond_to do |format|
      format.html{redirect_to :back}
      format.js
    end
  end

  def unfavourite

    @favourite = @post.find_my_favourite(current_user)
    if @favourite
      @favourite.destroy
    end
    respond_to do |format|
      format.html {redirect_to :back}
      format.js {render "favourite"}
    end
  end

  def like
    @like = @post.find_my_like(current_user)
    unless @like
      @like = Like.create!(:post => @post, :user => current_user)
    end

    respond_to do |format|
      format.html{redirect_to :back}
      format.js
    end
  end

  def dislike
    @like = @post.find_my_like(current_user)
    @like.destroy if @like

    respond_to do |format|
      format.html{redirect_to :back}
      format.js {render "like"}
    end
  end

  def subscribe
    @subscribe = @post.find_my_subscribe(current_user)
    unless @subscribe
      @subscribe = Subscribe.create!(:post => @post, :user => current_user)
    end

    respond_to do |format|
      format.html{ redirect_to :back }
      format.js
    end
  end

  def unsubscribe
    @subscribe = @post.find_my_subscribe(current_user)
    @subscribe.destroy if @subscribe

    respond_to do |format|
      format.html{ redirect_to :back }
      format.js{ render "subscribe"}
    end
  end

  protected

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :clicked, :status, :logo, :category_ids => [])
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_favourite.html.erb
<% unless @post.find_my_favourite(current_user) %>
  <%= link_to "Favourite", favourite_post_path(@post), :method => :post, :remote => true, :class => "btn btn-primary"%>
<%else%>
  <%= link_to "Unfavourite", unfavourite_post_path(@post), :method => :post, :remote => true, :class => "btn btn-primary"%>
<%end%> <%=@post.favourite_by.count%>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>


<div class="form-group">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <%= f.label :content, "Content" %>
  <%= f.text_area :content %>
</div>

<div class="form-group">
  <%= f.label :logo, "LOGO檔案" %>
  <%= f.file_field :logo %>
  <% if @post.logo.exists? %>
    <%= check_box_tag "destroy_logo", "1" %> 刪除檔案
  <% end %>
</div>

<div>
  <%= f.label :status, "Status:" %>
  <%= f.select :status, [["draft", "draft"],["release", "release"]] %>
</div>

app/views/posts/_like.html.erb
<% unless @post.find_my_like(current_user) %>
  <%= link_to "Like", like_post_path(@post), :method => :post, :remote => true, :class => "btn btn-primary"%>
<%else%>
  <%= link_to "Dislike", dislike_post_path(@post), :method => :post, :remote => true, :class => "btn btn-primary"%>
<%end%> <%=@post.likes_by.count%>

app/views/posts/_subscribe.html.erb
<% unless @post.find_my_subscribe(current_user) %>
  <%= link_to "訂閱", subscribe_post_path(@post), :method => :post, :remote => true, :class => "btn btn-primary" %>
<% else %>
  <%= link_to "取消訂閱", unsubscribe_post_path(@post), :method => :post, :remote => true, :class => "btn btn-danger" %>
<% end %><%= @post.subscribes_by.count%>

app/views/posts/about.html.erb
<h1>About Page</h1>

<p>Users: <%= @users.count %></p>
<p>Posts: <%= @posts.count %></p>
<p>Comments: <%= @comments.count %></p>

<%= link_to "Back to Index", posts_path %>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>

  <%= render :partial => "form", :locals => {:f => f} %>

  <%= f.submit "Update" %>

<% end %>

<%= link_to "Back to Index", posts_path %>

app/views/posts/favourite.js.erb
$("#favourite-block").html("<%=j render(:partial => "favourite")%>");

app/views/posts/index.html.erb
<h1>Forum</h1>

<%= link_to 'Sort by Ruby', posts_path(:sort => "Ruby") %>
<%= link_to 'Sort by Perl', posts_path(:sort => "Perl") %>
<%= link_to 'Sort by Java', posts_path(:sort => "Java") %>
<%= link_to 'None', posts_path %>

<br><br>
<p><%= link_to "New Post", new_post_path %></p>
<p><%= link_to 'Order by lastest comment time', posts_path(:order => 'last_comment_time') %></p>
<p><%= link_to 'Order by comment number', posts_path(:order =>'comment_number')%></p>
<p><%= link_to 'Order by clicks', posts_path(:order => 'topic_clicks') %></p>
<br><br>


<table class="table">

  <tr>
    <td>Topic</td>
    <td>User</td>
    <td>Post ID</td>
    <td>Comments</td>
    <td>Clicks</td>
    <td>Status</td>
    <td>Last comment time</td>

  </tr>

  <% @posts.each do |post|%>

    <tr>
      <td><%= link_to post.title, post_path(post)%></td>
      <td><%= link_to post.user.email, profile_info_path(:id => post.user.id) %></td>
      <td><%= post.id %></td>
      <td><%= post.comments.count %></td>
      <td><%= post.clicked %></td>
      <td><%= post.status %></td>
      <td>
        <% if post.comments.count != 0 %>
          <%= post.comments.last.updated_at %>
        <% else %>
            No comments
        <% end %>
      </td>
      <% if current_user && (current_user.author?(post)||current_user.admin?)%>
        <td><%= link_to "Edit", edit_post_path(post), :class => "btn btn-primary" %></td>
        <td><%= link_to "Delete", post_path(post), :method => :delete, :class => "btn btn-danger", :data => {:confirm => "Are you sure?"} %></td>
      <%end%>
    </tr>
  <% end %>
</table>



<%= paginate @posts %>

app/views/posts/like.js.erb
$("#like-block").html("<%= j render(:partial =>"like") %>");

app/views/posts/new.html.erb
<%= form_for @post, :url => posts_path, :class => "form" do |f|%>

  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= f.submit "Create", :class =>"btn btn-primary"%>


<% end %>

app/views/posts/show.html.erb
<p>Title: <%= @post.title%></p>
<p><%= @post.content%></p>
<p><%= @post.user.email%></p>

<div class="favourite pull-right">
  <% if current_user%>
    <span id ="favourite-block"%>
      <%= render "favourite"%>
    </span>
  <%end%>
</div>

<div class="like pull-right">
  <% if user_signed_in?%>
    <span id="like-block">
      <%= render "like"%>
    </span>
  <%end%>
</div>

<div class="like pull-right">
  <% if user_signed_in? %>
    <span id="subscribe-block"%>
      <%= render "subscribe" %>
    </span>
  <% end %>
</div>

<div class="facebood-good">
<iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&width=200&layout=button_count&action=like&size=large&show_faces=false&share=true&height=46&appId=1057048347714832" width="200" height="46" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
</div>

<p>Category:
  <% @post.categories.each do |g| %>
    <%= g.name %>
  <% end %>
</p>
<br>

<% if @post.logo.exists? %>
  <%= link_to @post.logo.url, :target => "_blank" do %>
    <%= image_tag(@post.logo.url(:thumb)) %>
  <% end %>
<% end %>

<table class="table">
  <tr><%="People who like:"%></tr>
  <h5>
    <tr>
    <% @post.likes_by.each do |l| %>
      <td><%= l.email %></td>
    <% end %>
    </tr>
  </h5>
</table>

<% if current_user %>
  <%= link_to "New Comment", new_post_comment_path(@post)%>
<%end%>


<p>Total comments:<%= @post.comments.count%></p>

<table class="table">
  <tr>
    <td>Comment:</td>

  </tr>
  <% @post.comments.each do |c|%>
    <tr>

      <td><%= c.content %></td>
      <td>
        <% if c.logo.exists? %>
          <%= link_to c.logo.url, :target => "_blank" do %>
            <%= image_tag(c.logo.url(:thumb)) %>
          <% end %>
        <% end %>
      </td>
      <td><%#=c.user.email%></td>
      <% if current_user && (current_user.author?(@post)||current_user.admin?)%>
        <td><%= link_to "Edit", edit_post_comment_path(@post, c), :class => "btn btn-primary"%></td>
        <td><%= link_to "Delete", post_comment_path(@post, c), :method => :delete, :class => "btn btn-danger", :data => {:confirm => "Are you sure?"} %></td>
      <%end%>
    </tr>
  <%end%>
</table>


<%= link_to "Back to Index", posts_path %>

app/views/posts/subscribe.js.erb
$("#subscribe-block").html("<%=j render(:partial => "subscribe") %>");