config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :posts do
    resources :comments

    collection do
        get :about
    end

    member do
      post :favourite
      post :unfavourite
      post :like
      post :dislike
      post :subscribe
      post :unsubscribe
    end

  end
  get '/profile/:id' => 'profiles#info', :as => "profile_info"

  namespace :admin do
    resources :posts # default ,:controller => "admin::posts"
    resources :users
    resources :categories
  end

  root :to => 'posts#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
 <html>
 <head>
   <!-- if @page_title is set then show, or show "Event application"-->
   <title><%=@page_title || "Post application"%></title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= csrf_meta_tags %>
 </head>
 <body>

   <div class="container">
     <div class="row">
       <div class="col-md-12">



         <% if flash[:notice].present? %>
           <div class ="alert alert-success" role="alert">
             <%= flash[:notice] %>
           </div>
         <% end %>

         <% if flash[:alert].present? %>
           <div class ="alert alert-danger" role="alert">
             <%= flash[:alert] %>
           </div>
         <% end %>

         <%= yield %>

         <%= link_to 'Index', posts_path %>
       </div>
     </div>
   </div>

 </body>
 </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= link_to "About", about_posts_path %>


  <title>Forum Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if current_user%>
    <p>Hi,<%=current_user.email%></p>
  <%end%>
  <% if current_user %>
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    <%= link_to('帳號設定', edit_user_registration_path(:user))%>|
    <%= link_to('修改密碼', edit_user_registration_path(:user)) %> |
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
  <% else %>
    <%= link_to('註冊', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %> |
    <%= link_to "登入 Facebook", user_facebook_omniauth_authorize_path%>
  <% end %>

<%= yield %>

<p>
  <% if current_user && current_user.admin?%>
    <%= link_to "Admin", admin_posts_path, :class=>"btn btn-danger" %>
  <%end%>
</p>

</body>
</html>